### ISSUE TITLE
where is the data ? i can't find it

### ISSUE THREAD

**Issue by lolbhw** [iRB-Lab/PPG-N-Back-Clip#1]
hi,there is no such data as you mentioned? would you upload it soon? thank you !!!!

**Comment by iROCKBUNNY** [comment]
The data is not available for the moment.

**Comment by lolbhw** [comment]
ok, so the model will work if i have some data? I mean is the code  completed ,right?

**Comment by iROCKBUNNY** [comment]
The models should work under correct configurations. However, this repository doesn’t include the complete project, especially the data sets. Anyway, if you happen to have the correct data with appropriate configurations, everything should be fine.

**Comment by lolbhw** [comment]
Can you share an example data file, so that we can figure out what configuration we need in order to run the code.
Thanks

**Comment by iROCKBUNNY** [comment]
I cannot share you any data file, but you can find the sample format in `README.md`.
